### ISSUE TITLE
Provide an info about the lib

### ISSUE THREAD

**Issue by paluh** [robertdp/purescript-react-store#4]
Hi,

Thanks a lot for building this hook library!

I'm a bit new to hooks and from my perspective it would be really cool to have some project objectives in the README ;-)
Showing problematic cases which this lib solves and comparison against `useReducer`, simple `useReducer` + `useAff` or `useAffReducer` could be really helpful (like in [this thread](https://github.com/spicydonuts/purescript-react-basic-hooks/issues/6) which I'm trying to grasp currently).

**Comment by robertdp** [comment]
Something like this? https://github.com/robertdp/purescript-react-store/blob/master/README.md

**Comment by paluh** [comment]
Wow! This is really cool. Thanks a lot!
